- hosts: all

  tasks:
    - name: install python3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes
      tags: [prepare]

    - name: install pip-docker
      ansible.builtin.include_role:
        name: geerlingguy.pip
        apply:
          become: yes
      vars:
        pip_executable: pip3
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
      tags: [prepare]

    - name: prepare environment file
      ansible.builtin.template:
        src: ./templates/.env.redmine.j2
        dest:  "{{ansible_env.HOME}}/.env.redmine"
      become: yes
      tags: [deploy]

    - name: start redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - "80:3000"
        env_file: "{{ansible_env.HOME}}/.env.redmine"
      tags: [deploy]