- hosts: all

  tasks:
    - name: install python3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes
      tags: [prepare]

    - name: install pip-docker
      ansible.builtin.include_role:
        name: geerlingguy.pip
        apply:
          become: yes
      vars:
        pip_executable: pip3
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
      tags: [prepare]

      become: yes
