- hosts: all
  gather_facts: no
  
  pre_tasks:
    - name: install python3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes
  
  roles:
    - role: geerlingguy.pip
      vars:
          pip_executable: pip3
          pip_package: python3-pip
          pip_install_packages:
            - name: docker
      become: yes
